sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - 0.6.x

php:
  - 7.0
  - 5.6

cache:
  - composer
  - $HOME/.composer/cache

env:
  global:
    - WP_CLI_BIN_DIR=/tmp/wp-cli-phar

before_script:
  - bash bin/install-package-tests.sh
  - composer install
  - bash bin/prepare.sh

script: ./vendor/bin/behat
